hokim_qabuli/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

# urlpatterns = i18n_patterns(
#
#
# )
urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls')),
    url('bot/', include(u'telegrambot.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'panel'

urlpatterns = [


    path('login/', admin_login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # MAHALLA
    path("mahalla/", MahallaView.as_view(), name="mahalla"),
    path("mahalla_yaratish/", MahallaCreateView.as_view(), name="mahalla_create"),
    path("mahalla/<int:pk>/", MahallaUpdateView.as_view(), name="mahalla_update"),
    path("mahalla_uchirish/<int:pk>/", MahallaDeleteView.as_view(), name="mahalla_delete"),

    path("mahalla_filter/", ajax_mahalla, name="ajax_mahalla"),

    # MUAMMO TURI
    path("muammo/", MuammoView.as_view(), name="muammo"),
    path("muammo_yaratish/", MuammoCreateView.as_view(), name="muammo_create"),
    path("muammo/<int:pk>/", MuammoUpdateView.as_view(), name="muammo_update"),
    path("muammo_uchirish/<int:pk>/", MuammoDeleteView.as_view(), name="muammo_delete"),

    path("muammo_filter/", ajaxfilter, name="muammo_filter"),

    # CATEGORIYA
    path("kategoriya/", KategoriyaView.as_view(), name="kategoriya"),
    path("kategoriya_yaratish/", KategoriyaCreateView.as_view(), name="kategoriya_create"),
    path("kategoriya/<int:pk>/", KategoriyaUpdateView.as_view(), name="kategoriya_update"),
    path("kategoriya_uchirish/<int:pk>/", KategoriyaDeleteView.as_view(), name="kategoriya_delete"),
    path("ajax/filter_category", ajax_filter_category, name="ajax_filter_category"),

    # Foydalanuvchi
    path("foydalanuvchi/", FoydalanuvchiView.as_view(), name="foydalanuvchi"),
    path("foydalanuvchi/search/", FoydalanuvchiSearchView.as_view(), name="foydalanuvchi_search"),
    path("foydalanuvchi/detail/<int:pk>", FoydalanuvchiDetailView.as_view(), name="foydalanuvchi_detail"),
    path("foydalanuvchi/update/<int:pk>", FoydalanuvchiUpdateView.as_view(), name="foydalanuvchi_update"),

    # HUDUD
    path("hudud/", HududView.as_view(), name="hudud"),
    path("hudud_yaratish/", HududCreateView.as_view(), name="hudud_create"),
    path("hudud/<int:pk>/", HududUpdateView.as_view(), name="hudud_update"),
    path("hudud_uchirish/<int:pk>/", HududDeleteView.as_view(), name="hudud_delete"),

    # MUROJATCHI
    path("murojatchi/", MurojatchiView.as_view(), name="murojatchi"),
    path("murojatchi/search/", MurojatchiSearchView.as_view(), name="murojatchi_search"),
    path("murojatchi/see/<int:pk>", MurojatchiDetailView.as_view(), name="murojatchi_detail"),
    path("murojatchi/<int:pk>/", MurojatchiReplyMessageView.as_view(), name="murojatchi_reply"),
    path("murojatchi_uchirish/<int:pk>/", MurojatchiDeleteView.as_view(), name="murojatchi_delete"),


    # QABUL
    path("qabul/", QabulView.as_view(), name="qabul"),

    # Statistics
    path('statistics/', StatisticsView.as_view(), name='statistics'),
    path('statistics/<int:id>', StatisticsDetailView.as_view(), name='statistics_detail'),


    # ACCEPTED APPLICANTS
    path("accepted/", AcceptedView.as_view(), name="accepted"),
    path("accepted/search/", AcceptedSearchView.as_view(), name="accepted_search"),
    path("accepted/see/<int:pk>", AcceptedDetailView.as_view(), name="accepted_detail"),
    path("accepted/<int:pk>", AcceptedUpdateView.as_view(), name="accepted_update"),


    # Ajax
    path("murojatchi_filter/", murojatchi_filter, name="murojatchi_filter"),


    # Statistics
    path('statistics/', StatisticsView.as_view(), name= 'statistics')

   # path('ajax/mahalla_muammo/', ajax_mahalla_muammo, name='ajax_mahalla_muammo'),


]

panel/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Mahalla(models.Model):
    title = models.CharField(_("Mahalla nomi"), max_length=256, null=True)
    region = models.CharField(verbose_name='Tuman', max_length=255, null=True)
    title_ru = models.CharField(_("Mahalla nomi_ru"), max_length=256, null=True)
    title_uz = models.CharField(_("Mahalla nomi_uz"), max_length=256, null=True)
    token = models.CharField(max_length=1024, null=True)
    location = models.CharField(_("Manzil"), max_length=256, null=True)
    phone = models.CharField(_("Telefon"), max_length=13, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Mahalla')
        verbose_name_plural = _('Mahallalar')


class MuammoManager(models.Manager):
    def get_by_natural_key(self, title):
        return self.get(title=title)


class Muammo(models.Model):
    title = models.CharField(_("Muammo nomi"), max_length=300)

    objects = MuammoManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Muammo nomi")
        verbose_name_plural = _('Muammolar')

    def natural_key(self):
        return self.title


class SubMuammo(models.Model):
    title = models.ForeignKey(Muammo, on_delete=models.CASCADE, default='')
    category = models.CharField(_("Kategoriya"), max_length=64, default="Default")

    def __str__(self):
        return str(self.category)

    class Meta:
        verbose_name = _("Kategoriya nomi")
        verbose_name_plural = _('Kategoriyalar')


class Hudud(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(_("Hudud"), max_length=128)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Hudud")
        verbose_name_plural = _('Hudud')


class Murojatchi(models.Model):
    MUROJATCHI_STATUSI = (
        ("ko'rib chiqilmagan", _("ko'rib chiqilmagan")),
        ("ko'rib chiqilmoqda", _("ko'rib chiqilmoqda")),
        ("ko'rib chiqildi", _("ko'rib chiqildi")),
        ("rad etildi", _("rad etildi")),
    )
    MUROJAT_TURI = (

        ("appeal", _("Murojat")),
        ("admission", _("Qabul")),
    )

    GENDER = (
        (1, _("Erkak")),
        (2, _("Ayol")),
    )

    telegram_id = models.PositiveBigIntegerField(_("Telegram ID"), blank=True, null=True)
    fullname = models.CharField(_("Ism Sharifi"), max_length=256, blank=True, null=True)
    username = models.CharField(_("Username"), max_length=32, blank=True, null=True)
    hudud = models.ForeignKey(Hudud, on_delete=models.CASCADE, blank=True, null=True)
    mahalla = models.ForeignKey(Mahalla, on_delete=models.CASCADE, blank=True, null=True)
    murojat_turi = models.CharField(max_length=16, choices=MUROJAT_TURI, blank=True, null=True)
    muammo = models.ForeignKey(Muammo, on_delete=models.CASCADE, blank=True, null=True)
    category = models.ForeignKey(SubMuammo, on_delete=models.CASCADE, blank=True, null=True)
    media = models.FileField(_("Media"), upload_to='muammo_media/', blank=True, null=True)
    location = models.CharField(_("Manzil"), max_length=300, blank=True, null=True)
    description = models.TextField(_("Murojat Matni"), null=True, blank=True)
    phone = models.CharField(_("Telefon"), max_length=13, blank=True, null=True)

    reply_message = models.TextField(_("Javob Matni"), default=_("Javob berilmagan"), blank=True, null=True)
    created = models.DateField(_("Murojat Sanasi"), auto_now_add=True, null=True, blank=True)
    updated = models.DateField(_("O'zgartish Kiritilgan Sana"), auto_now_add=True, null=True, blank=True)
    status = models.CharField(_("Murojatchi Statusi"), max_length=32, choices=MUROJATCHI_STATUSI,
                              default=MUROJATCHI_STATUSI[0][0], null=True, blank=True)

    year_of_birth = models.PositiveIntegerField(_("Tug'ilgan yil"),  null=True, blank=True)
    month_of_birth = models.CharField(_("Tug'ilgan oy"), max_length=256, null=True, blank=True)
    day_of_birth = models.CharField(_("Tug'ilgan kun"), max_length=256, null=True, blank=True)
    gender = models.PositiveBigIntegerField(_("Gender"), choices=GENDER, null=True, blank=True)

    def __str__(self):

        return f"{str(self.fullname)}"


    class Meta:
        verbose_name = _('Murojatchi')
        verbose_name_plural = _('Murojatchilar')



RECEPTION_STATUS = (
    (1, _("Ko'rib Chiqildi")),
    (2, _("Ko'rib Chiqilmoqda")),
    (3, _("Ko'rib Chiqilmagan")),
)

class ProfileSuggestion(models.Model):
    GENDER = (
        (1, _("Erkak")),
        (2, _("Ayol")),
    )
    id = models.BigAutoField(primary_key=True)
    telegram_id = models.PositiveBigIntegerField(_("Telegram ID"), blank=True, null=True)
    fullname = models.CharField(_("Ism Sharifi"), max_length=256, blank=True, null=True)
    phone = models.CharField(_("Telefon"), max_length=13, blank=True, null=True)
    year_of_birth = models.CharField(_("Tug'ilgan yil"), max_length=256, null=True, blank=True)
    month_of_birth = models.CharField(_("Tug'ilgan oy"), max_length=256, null=True, blank=True)
    day_of_birth = models.CharField(_("Tug'ilgan kun"), max_length=256, null=True, blank=True)
    gender = models.PositiveBigIntegerField(_("Gender"), choices=GENDER, null=True, blank=True)



class Reception(models.Model):
    title = models.CharField(_("Qabul Nomi"), max_length=256)
    users = models.ManyToManyField(Murojatchi, blank=True)
    appointment = models.DateField(null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    status = models.IntegerField(default=3, choices=RECEPTION_STATUS, null=True,blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Qabul')
        verbose_name_plural = _('Qabullar')

panel/forms.py
from django import forms
from panel.models import *


class MahallaForm(forms.ModelForm):
    class Meta:
        model = Mahalla
        fields = ("title", "location", "phone")


class MuammoForm(forms.ModelForm):
    class Meta:
        model = Muammo
        fields = ("title",)


class HududForm(forms.ModelForm):
    class Meta:
        model = Hudud
        fields = ("title",)


class KategoriyaForm(forms.ModelForm):
    class Meta:
        model = SubMuammo
        fields = ("title", "category")
        widgets = {
            'title': forms.Select(attrs={'class': 'form-control'})
        }


class FoydalanuvchiForm(forms.ModelForm):
    class Meta:
        model = Murojatchi
        fields = ("telegram_id", "username", "fullname", "phone")


class MurojatchiForm(forms.ModelForm):
    class Meta:
        model = Murojatchi
        fields = ("fullname", "status")


class MurojatchiReplyMessageForm(forms.ModelForm):
    class Meta:
        model = Murojatchi
        fields = ("reply_message", "status")
        widgets = {
            'status': forms.Select(attrs={'class': 'form-control px-1 ml-3 mb-2'}),
        }


class ReceptionForm(forms.ModelForm):
    telegram_id = forms.ModelMultipleChoiceField(
        queryset=Murojatchi.objects.all()
    )

    class Meta:
        model = Reception

        fields = ['title', 'users', 'appointment', 'status']

        widgets = {
            'status': forms.Select(attrs={'class':'form-control'})
        }

templates/panel/murojatchi/search.html
{% extends 'panel/layout/layout.html' %}
{% load static i18n %}

{% block head %}
{% endblock %}

{% block body %}
    {#    {% if user|has_role:"admin_temp" %}#}
    {% include 'panel/inc/sidebar.html' %}
    {#    {% endif %}#}
    <!-- BEGIN: Content-->

    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <h1 class="text-center">{% trans "Murojatlar Qidiruv" %}</h1>
            <div class="content-header row">
                <div class="content-header-left col-12 mb-2 mt-1">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <div class="heading-elements">
                                <ul class="list-inline mb-0 main-list-heading">
                                    <li class="main-searchh">
                                        {% comment %} {% if request.GET.q %}
                                            <fieldset class="position-relative">
                                                <form action="" method="GET">
                                                    <input type="text" name="q" class="form-control single-daterange" placeholder="{% trans 'Izlash' %}" value="{{ request.GET.q }}"/>
                                                    <input type="text" name="q" class="form-control single-daterange" placeholder="{% trans 'Izlash' %}" value="rad"/>
                                                    <div class="form-control-position">
                                                        <a href="{% url 'navigation' %}"><i
                                                                class="bx bx-x font-medium-2"></i></a>
                                                    </div>
                                                </form>
                                            </fieldset>
                                        {% else %}
                                            <fieldset class="has-icon-left">
                                                <form action="" method="GET">
                                                    <input type="text" name="q" class="form-control single-daterange" placeholder="{% trans 'Izlash' %}" value="{{ request.GET.q }}"/>
                                                    <input type="text" name="q" class="form-control single-daterange" placeholder="{% trans 'Izlash' %}" value="rad0"/>
                                                    <div class="form-control-position">
                                                        <i class="bx bx-search font-medium-2"></i>
                                                    </div>
                                                </form>

                                            </fieldset>
                                        {% endif %}{% endcomment %}
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- table Transactions start -->
                <a style="float: right;margin-bottom: 15px;" href="{% url 'panel:murojatchi' %}">
                    <button class="btn btn-info"><i class="fa fa-angle-double-left"
                                                    style="padding-right: 3px;font-size: 20px;"
                                                    aria-hidden="true"></i> {% trans 'Orqaga' %}</button>
                </a>
                <br><br>
                <hr>
                <p class="font-weight-bold">{% trans 'Murojatlar Soni:' %} {{ murojatchi_list.count }}</p>

                <section id="table-transactions">
                    <div class="card">
                        <!-- datatable start -->
                        <div class="table-responsive">
                            <table id="table-extended-transactions" class="table mb-0">
                                <thead>
                                <tr>
                                    <th class="pr-2">№</th>
                                    <th class="pl-0">{% trans 'Murojatchi' %}</th>
                                    <th class="pl-2">{% trans 'Hudud' %}</th>
                                    <th class="pl-2">{% trans 'Mahalla' %}</th>
                                    <th class="pl-2">{% trans 'Muammo' %}</th>
                                    <th class="pl-2">{% trans 'Murojat Vaqti' %}</th>
                                    <th class="pl-2">{% trans 'Status' %}</th>
                                    <th class="pl-2">{% trans 'Amallar' %}</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for murojatchi in object_list %}
                                    <tr>
                                        <td class="pr-2">{{ forloop.counter }}</td>
                                        <td class="pl-0">
                                            <a href="{% url 'panel:murojatchi_reply' murojatchi.id %}">{{ murojatchi.fullname|safe | truncatechars:"150" }}</a>
                                        </td>
                                        <td class="text-left">{{ murojatchi.hudud }}</td>
                                        <td class="text-left">{{ murojatchi.mahalla }}</td>
                                        <td class="text-left">{{ murojatchi.muammo }}</td>


                                        <td class="text-left">{{ murojatchi.created | date:"d.m.Y" }}</td>
                                        <td class="text-left">{{ murojatchi.status }}</td>


                                        <td class="text-center amallar">
                                            <a class="mr-1" href="{% url 'panel:murojatchi_detail' murojatchi.id %}"><i
                                                    class="fa fa-eye" style="font-size: 19px;"
                                                    aria-hidden="true"></i></a>
                                            <a href="{% url 'panel:murojatchi_reply' murojatchi.id %}"><i
                                                    class="fa fa-edit" style="font-size: 19px;" aria-hidden="true"></i></a>


                                            {#                                            <div class="dropdown">#}
                                            {#                                                <span class="bx bx-dots-vertical-rounded font-medium-3 dropdown-toggle nav-hide-arrow cursor-pointer"#}
                                            {#                                                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"#}
                                            {#                                                      role="menu"></span>#}
                                            {#                                                <div class="dropdown-menu dropdown-menu-right">#}
                                            {#                                                    <a class="dropdown-item"#}
                                            {#                                                       href="{% url 'panel:murojatchi_update' murojatchi.id %}"><i#}
                                            {#                                                            class="bx bx-edit-alt mr-1"></i>{% trans "O'zgartirish" %}</a>#}
                                            {##}
                                            {#                                                    <a class="dropdown-item" data-id="{{ murojatchi.id }}"#}
                                            {#                                                       href="{% url 'panel:murojatchi_delete' murojatchi.id %}"><i#}
                                            {#                                                            class="bx bx-trash mr-1"></i>#}
                                            {#                                                        {% trans "O'chirish" %}</a>#}
                                            {#                                                </div>#}

                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        <!-- datatable ends -->
                    </div>

                </section>

                <!-- table Transactions end -->
            </div>
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
{% endblock %}

{% block js %}
{% endblock %}