hokim_qabuli/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

# urlpatterns = i18n_patterns(
#
#
# )
urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls')),
    url('bot/', include(u'telegrambot.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'panel'

urlpatterns = [


    path('login/', admin_login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # MAHALLA
    path("mahalla/", MahallaView.as_view(), name="mahalla"),
    path("mahalla_yaratish/", MahallaCreateView.as_view(), name="mahalla_create"),
    path("mahalla/<int:pk>/", MahallaUpdateView.as_view(), name="mahalla_update"),
    path("mahalla_uchirish/<int:pk>/", MahallaDeleteView.as_view(), name="mahalla_delete"),

    path("mahalla_filter/", ajax_mahalla, name="ajax_mahalla"),

    # MUAMMO TURI
    path("muammo/", MuammoView.as_view(), name="muammo"),
    path("muammo_yaratish/", MuammoCreateView.as_view(), name="muammo_create"),
    path("muammo/<int:pk>/", MuammoUpdateView.as_view(), name="muammo_update"),
    path("muammo_uchirish/<int:pk>/", MuammoDeleteView.as_view(), name="muammo_delete"),

    path("muammo_filter/", ajaxfilter, name="muammo_filter"),

    # CATEGORIYA
    path("kategoriya/", KategoriyaView.as_view(), name="kategoriya"),
    path("kategoriya_yaratish/", KategoriyaCreateView.as_view(), name="kategoriya_create"),
    path("kategoriya/<int:pk>/", KategoriyaUpdateView.as_view(), name="kategoriya_update"),
    path("kategoriya_uchirish/<int:pk>/", KategoriyaDeleteView.as_view(), name="kategoriya_delete"),
    path("ajax/filter_category", ajax_filter_category, name="ajax_filter_category"),

    # Foydalanuvchi
    path("foydalanuvchi/", FoydalanuvchiView.as_view(), name="foydalanuvchi"),
    path("foydalanuvchi/search/", FoydalanuvchiSearchView.as_view(), name="foydalanuvchi_search"),
    path("foydalanuvchi/detail/<int:pk>", FoydalanuvchiDetailView.as_view(), name="foydalanuvchi_detail"),
    path("foydalanuvchi/update/<int:pk>", FoydalanuvchiUpdateView.as_view(), name="foydalanuvchi_update"),

    # HUDUD
    path("hudud/", HududView.as_view(), name="hudud"),
    path("hudud_yaratish/", HududCreateView.as_view(), name="hudud_create"),
    path("hudud/<int:pk>/", HududUpdateView.as_view(), name="hudud_update"),
    path("hudud_uchirish/<int:pk>/", HududDeleteView.as_view(), name="hudud_delete"),

    # MUROJATCHI
    path("murojatchi/", MurojatchiView.as_view(), name="murojatchi"),
    path("murojatchi/search/", MurojatchiSearchView.as_view(), name="murojatchi_search"),
    path("murojatchi/see/<int:pk>", MurojatchiDetailView.as_view(), name="murojatchi_detail"),
    path("murojatchi/<int:pk>/", MurojatchiReplyMessageView.as_view(), name="murojatchi_reply"),
    path("murojatchi_uchirish/<int:pk>/", MurojatchiDeleteView.as_view(), name="murojatchi_delete"),


    # QABUL
    path("qabul/", QabulView.as_view(), name="qabul"),

    # Statistics
    path('statistics/', StatisticsView.as_view(), name='statistics'),
    path('statistics/<int:id>', StatisticsDetailView.as_view(), name='statistics_detail'),


    # ACCEPTED APPLICANTS
    path("accepted/", AcceptedView.as_view(), name="accepted"),
    path("accepted/search/", AcceptedSearchView.as_view(), name="accepted_search"),
    path("accepted/see/<int:pk>", AcceptedDetailView.as_view(), name="accepted_detail"),
    path("accepted/<int:pk>", AcceptedUpdateView.as_view(), name="accepted_update"),


    # Ajax
    path("murojatchi_filter/", murojatchi_filter, name="murojatchi_filter"),


    # Statistics
    path('statistics/', StatisticsView.as_view(), name= 'statistics')

   # path('ajax/mahalla_muammo/', ajax_mahalla_muammo, name='ajax_mahalla_muammo'),


]

panel/forms.py
from django import forms
from panel.models import *


class MahallaForm(forms.ModelForm):
    class Meta:
        model = Mahalla
        fields = ("title", "location", "phone")


class MuammoForm(forms.ModelForm):
    class Meta:
        model = Muammo
        fields = ("title",)


class HududForm(forms.ModelForm):
    class Meta:
        model = Hudud
        fields = ("title",)


class KategoriyaForm(forms.ModelForm):
    class Meta:
        model = SubMuammo
        fields = ("title", "category")
        widgets = {
            'title': forms.Select(attrs={'class': 'form-control'})
        }


class FoydalanuvchiForm(forms.ModelForm):
    class Meta:
        model = Murojatchi
        fields = ("telegram_id", "username", "fullname", "phone")


class MurojatchiForm(forms.ModelForm):
    class Meta:
        model = Murojatchi
        fields = ("fullname", "status")


class MurojatchiReplyMessageForm(forms.ModelForm):
    class Meta:
        model = Murojatchi
        fields = ("reply_message", "status")
        widgets = {
            'status': forms.Select(attrs={'class': 'form-control px-1 ml-3 mb-2'}),
        }


class ReceptionForm(forms.ModelForm):
    telegram_id = forms.ModelMultipleChoiceField(
        queryset=Murojatchi.objects.all()
    )

    class Meta:
        model = Reception

        fields = ['title', 'users', 'appointment', 'status']

        widgets = {
            'status': forms.Select(attrs={'class':'form-control'})
        }

panel/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
import requests
from django.core import serializers
from django.db.models import Q
from django.http import JsonResponse, HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DeleteView, UpdateView, CreateView, DetailView
from django.http import request, JsonResponse, HttpResponse, HttpResponseRedirect, HttpRequest
from .forms import *
from .models import *
from datetime import datetime


def admin_login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                ''' Begin reCAPTCHA validation '''
                recaptcha_response = request.POST.get('g-recaptcha-response')

                data = {
                    'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                    'response': recaptcha_response
                }
                r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
                result = r.json()
                ''' End reCAPTCHA validation '''

                if result['success']:
                    login(request, user)
                    return redirect('panel:murojatchi')
                else:
                    messages.error(request, 'Yaroqsiz reCAPTCHA kiritildi')
                    return redirect('panel:login')
            else:
                messages.error(request, "Sizning akkountingiz bloklangan")
                return redirect('panel:login')
        else:
            messages.error(request, "Noto'g'ri kirish tafsilotlari berildi")
            return redirect('panel:login')

    elif request.method == 'GET':
        return render(request, 'panel/AdminLogin/index.html')



class StatisticsView(LoginRequiredMixin, ListView):
    queryset = Murojatchi.objects.all()
    template_name = 'panel/statistics/statistics.html'

    def get_context_data(self, **kwargs):
        context = super(StatisticsView, self).get_context_data(**kwargs)
        context['muammolar'] = Muammo.objects.all()
        context['a'] = Murojatchi.objects.all()
        return context

""" Mahalla Part """


class MahallaView(LoginRequiredMixin, ListView):
    template_name = 'panel/mahalla/index.html'
    context_object_name = 'mahalla_list'
    queryset = Mahalla.objects.all()
    paginate_by = 10


class MahallaCreateView(LoginRequiredMixin, ListView):

    def get(self, request, *args, **kwargs):
        return render(request, 'panel/mahalla/create.html')

    def post(self, request):
        form = MahallaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('panel:mahalla')
        else:
            return render(request, 'panel/mahalla/create.html', {'form': form})


class MahallaUpdateView(LoginRequiredMixin, UpdateView):
    model = Mahalla
    template_name = "panel/mahalla/update.html"
    context_object_name = 'mahalla'
    form_class = MahallaForm
    success_url = reverse_lazy("panel:mahalla")


class MahallaDeleteView(LoginRequiredMixin, DeleteView):
    model = Mahalla
    success_url = reverse_lazy("panel:mahalla")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


""" End Mahalla Part """

""" Muammo Part """


class MuammoView(LoginRequiredMixin, ListView):
    template_name = 'panel/muammo/index.html'
    context_object_name = 'muammo_list'
    queryset = Muammo.objects.all()
    form = MuammoForm


class HududView(LoginRequiredMixin, ListView):
    template_name = 'panel/hudud/index.html'
    context_object_name = 'hudud_list'
    queryset = Hudud.objects.all()
    form = HududForm
    paginate_by = 10


class MuammoCreateView(LoginRequiredMixin, ListView):

    def get(self, request, *args, **kwargs):
        return render(request, 'panel/muammo/create.html')

    def post(self, request):
        form = MuammoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('panel:muammo')
        else:
            return render(request, 'panel/muammo/create.html', {'form': form})


class HududCreateView(LoginRequiredMixin, ListView):

    def get(self, request, *args, **kwargs):
        return render(request, 'panel/hudud/create.html')

    def post(self, request):
        form = HududForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('panel:hudud')
        else:
            return render(request, 'panel/hudud/create.html', {'form': form})


class MuammoUpdateView(LoginRequiredMixin, UpdateView):
    model = Muammo
    template_name = "panel/muammo/update.html"
    context_object_name = 'muammo'
    form_class = MuammoForm
    success_url = reverse_lazy("panel:muammo")


class HududUpdateView(LoginRequiredMixin, UpdateView):
    model = Hudud
    template_name = "panel/hudud/update.html"
    context_object_name = 'hudud'
    form_class = HududForm
    success_url = reverse_lazy("panel:hudud")


class MuammoDeleteView(LoginRequiredMixin, DeleteView):
    model = Muammo
    success_url = reverse_lazy("panel:muammo")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class HududDeleteView(LoginRequiredMixin, DeleteView):
    model = Hudud
    success_url = reverse_lazy("panel:hudud")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


""" End Muammo Part """

""" Murojatchi Part """


class MurojatchiView(LoginRequiredMixin, ListView):
    template_name = 'panel/murojatchi/index.html'
    context_object_name = 'murojatchi_list'
    queryset = Murojatchi.objects.all()
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(MurojatchiView, self).get_context_data(**kwargs)
        context['mahallalar'] = Mahalla.objects.all()
        context['muammolar'] = Muammo.objects.all()
        context['hududlar'] = Hudud.objects.all()

        return context


class MurojatchiSearchView(LoginRequiredMixin, ListView):
    template_name = 'panel/murojatchi/search.html'
    model = Murojatchi

    def get_queryset(self):
        queryset = Murojatchi.objects.all()
        if self.request.GET.get('fullname') != '':
            fullname = self.request.GET.get('fullname')
            queryset = self.model.objects.filter(fullname__icontains=fullname)
        if self.request.GET.get('phone') != '':
            phone = self.request.GET.get('phone')
            queryset &= self.model.objects.filter(phone__icontains=phone)
        if self.request.GET.get('mahalla') != '':
            mahalla = self.request.GET.get('mahalla')
            queryset &= self.model.objects.filter(mahalla_id=mahalla)
        if self.request.GET.get('murojat_turi') != '':
            murojat_turi = self.request.GET.get('murojat_turi')

            if murojat_turi == 'appeal':
                queryset &= self.model.objects.filter(murojat_turi=Murojatchi.MUROJAT_TURI[0][0])
            elif murojat_turi == 'admission':
                queryset &= self.model.objects.filter(murojat_turi=Murojatchi.MUROJAT_TURI[1][0])

        if self.request.GET.get('hudud') != '':
            hudud = self.request.GET.get('hudud')
            queryset &= self.model.objects.filter(hudud_id=hudud)
        if self.request.GET.get('muammo') != '':
            muammo = self.request.GET.get('muammo')
            queryset &= self.model.objects.filter(muammo_id=muammo)
        if self.request.GET.get('status') != '':
            status = self.request.GET.get('status')
            queryset &= self.model.objects.filter(status=status)
        return queryset


class MurojatchiDetailView(LoginRequiredMixin, DetailView):
    model = Murojatchi
    context_object_name = 'murojatchi'
    queryset = Murojatchi.objects.all()
    template_name = 'panel/murojatchi/see.html'


class StatisticsView(LoginRequiredMixin, ListView):
    queryset = Murojatchi.objects.all()
    template_name = 'panel/statistics/statistics.html'

    def get_context_data(self, **kwargs):
        context = super(StatisticsView, self).get_context_data(**kwargs)
        context['mahallalar'] = Mahalla.objects.all()
        context['muammolar'] = []
        for muammo in Muammo.objects.all():
            obj = {}

            obj['title'] = muammo.title
            obj['total'] = muammo.murojatchi_set.count()
            obj['completed'] = muammo.murojatchi_set.filter(status=Murojatchi.MUROJATCHI_STATUSI[2][0]).count()
            obj['completed_percent'] = int(0 if obj['total'] == 0 else obj['completed'] / obj['total'] * 100)
            obj['women'] = muammo.murojatchi_set.filter(gender=Murojatchi.GENDER[1][0]).count()
            obj['men'] = muammo.murojatchi_set.filter(gender=Murojatchi.GENDER[0][0]).count()
            curr_year = datetime.now().year  # 2021

            year_25 = muammo.murojatchi_set.filter(year_of_birth__gte=curr_year - 25).count()  # [1996 -> ]
            year_26_35 = muammo.murojatchi_set.filter(
                Q(year_of_birth__gte=curr_year - 35) & Q(year_of_birth__lte=curr_year - 26)).count()  # [1986-1995]
            year_36 = muammo.murojatchi_set.filter(year_of_birth__lte=curr_year - 36).count()  # [0 - 1985]
            obj['year_25_percent'] = round(0 if obj['total'] == 0 else year_25 / obj['total'] * 100, 2)
            obj['year_36_percent'] = round(0 if obj['total'] == 0 else year_36 / obj['total'] * 100, 2)
            obj['year_26_35_percent'] = round(0 if obj['total'] == 0 else year_26_35 / obj['total'] * 100, 2)

            context['muammolar'].append(obj)

templates/panel/hudud/index.html
{% extends 'panel/layout/layout.html' %}
{% load static i18n %}
{% block head %}
{% endblock %}
{% block custom_css %}
    <style>
        .pagination {
            display: inline-block;
        }

        .pagination a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
        }

    </style>
{% endblock %}
{% block body %}
    {#    {% if user|has_role:"admin_temp" %}#}
    {% include 'panel/inc/sidebar.html' %}
    {#    {% endif %}#}
    <!-- BEGIN: Content-->

    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <h1 class="text-center">{% trans 'Barcha Hududlar' %}</h1>
            <div class="content-header row">
                <div class="content-header-left col-12 mb-2 mt-1">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <div class="heading-elements">
                                <ul class="list-inline mb-0 main-list-heading">
                                    <li class="main-search">
                                        {% comment %} {% if request.GET.q %}
                                            <fieldset class="position-relative">
                                                <form action="" method="GET">
                                                    <input type="text" name="q" class="form-control single-daterange" placeholder="{% trans 'Izlash' %}" value="{{ request.GET.q }}"/>
                                                    <input type="text" name="q" class="form-control single-daterange" placeholder="{% trans 'Izlash' %}" value="rad"/>
                                                    <div class="form-control-position">
                                                        <a href="{% url 'navigation' %}"><i
                                                                class="bx bx-x font-medium-2"></i></a>
                                                    </div>
                                                </form>
                                            </fieldset>
                                        {% else %}
                                            <fieldset class="has-icon-left">
                                                <form action="" method="GET">
                                                    <input type="text" name="q" class="form-control single-daterange" placeholder="{% trans 'Izlash' %}" value="{{ request.GET.q }}"/>
                                                    <input type="text" name="q" class="form-control single-daterange" placeholder="{% trans 'Izlash' %}" value="rad0"/>
                                                    <div class="form-control-position">
                                                        <i class="bx bx-search font-medium-2"></i>
                                                    </div>
                                                </form>

                                            </fieldset>
                                        {% endif %}{% endcomment %}
                                    </li>
                                    <li class="add-new-button"><a class="btn btn-primary"
                                                                  href="{% url 'panel:hudud_create' %}"><i
                                            class="bx bxs-plus-square mr-1"></i>{% trans 'Yaratish' %}</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- table Transactions start -->
                <section id="table-transactions">
                    <div class="card">
                        <!-- datatable start -->
                        <div class="table-responsive">
                            <table id="table-extended-transactions" class="table mb-0">
                                <thead>
                                <tr>
                                    <th class="pr-2">№</th>
                                    <th class="pl-0">{% trans 'Hudud' %}</th>
                                    <th class="text-right">{% trans 'Amallar' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for hudud in hudud_list %}
                                    <tr>
                                        <td class="pr-2">{{ forloop.counter }}</td>
                                        <td class="pl-0">
                                            <a href="{% url 'panel:hudud_update' hudud.id %}">{{ hudud.title|safe | truncatechars:"150" }}</a>
                                        </td>
                                        <td class="text-right amallar">
                                             <a class="mr-2" href="{% url 'panel:hudud_update' hudud.id %}"><i class="fa fa-edit" style="font-size: 19px;" aria-hidden="true"></i></a>
                                            <a href="{% url 'panel:hudud_delete' hudud.id %}"><i class="fa fa-trash" style="font-size: 19px;" aria-hidden="true"></i></a>

                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- datatable ends -->
                    </div>
                </section>
               {% if is_paginated %}
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">&laquo;</a>
                            </li>
                        {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}

                        <li class="page-item"><a class="page-link" style="background-color: rgb(51,122,183);color: white;">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %} {% endfor %} {% if page_obj.has_next %}
                        <li class="page-item">
                            <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">&raquo;</a>
                        </li>
                    {% endif %}
                    </ul>
                {% endif %}
                <!-- table Transactions end -->
            </div>
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
{% endblock %}

{% block js %}
{% endblock %}